import type { Readable } from 'node:stream';

export interface StoredObjectMeta {
  key: string;
  size: number;
  modifiedAt: Date;
}

export interface ByteRange {
  start: number;
  end: number; // inclusive
}

export interface MultipartUpload {
  uploadId: string;
  key: string;
}

/**
 * Storage abstraction. Keys are POSIX-style relative paths generated by the
 * application (never user input). Local disk is implemented today; S3-compatible
 * stores (S3, R2, B2, MinIO) implement the same contract — see docs/ARCHITECTURE.md.
 */
export interface StorageService {
  readonly driver: 'local' | 's3';

  put(key: string, body: Readable | Buffer): Promise<StoredObjectMeta>;
  get(key: string, range?: ByteRange): Promise<{ stream: Readable; size: number }>;
  delete(key: string): Promise<void>;
  /** Recursively delete everything under a prefix. */
  deletePrefix(prefix: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  getMetadata(key: string): Promise<StoredObjectMeta | null>;
  /** Server-side move/rename (O(1) on the same local filesystem). */
  move(fromKey: string, toKey: string): Promise<void>;
  copy(fromKey: string, toKey: string): Promise<void>;
  /** Total bytes under a prefix (used for temp/export accounting). */
  sizeOfPrefix(prefix: string): Promise<{ bytes: number; files: number }>;

  /** Multipart API — used for direct-to-object-storage uploads. Local driver throws NotSupported. */
  createMultipartUpload(key: string): Promise<MultipartUpload>;
  completeMultipartUpload(upload: MultipartUpload, parts: { partNumber: number; etag: string }[]): Promise<StoredObjectMeta>;
  abortUpload(upload: MultipartUpload): Promise<void>;

  /** Signed, time-limited download URL. Returns null when the driver streams through the API (local). */
  getSignedDownloadUrl(key: string, opts: { expiresInSeconds: number; filename: string }): Promise<string | null>;

  /** Absolute local path for a key (local driver only; used by tus FileStore + ClamAV streaming). */
  localPath?(key: string): string;

  /** Capacity of the underlying volume, when known. */
  capacity(): Promise<{ totalBytes: number; freeBytes: number; usedBytes: number; path: string | null }>;
}

/** Well-known key prefixes. */
export const KEYS = {
  tus: 'tus',
  staging: 'staging',
  uploads: 'uploads',
  quarantine: 'quarantine',
  exports: 'exports',
  branding: 'branding',
  fileKey: (clientId: string, portalId: string, sessionId: string, storedFilename: string) =>
    `uploads/${clientId}/${portalId}/${sessionId}/${storedFilename}`,
  stagingKey: (storedFilename: string) => `staging/${storedFilename}`,
  quarantineKey: (storedFilename: string) => `quarantine/${storedFilename}`,
  exportKey: (exportId: string) => `exports/${exportId}.zip`,
};
